- name: Install Nginx
  become: yes
  apt: name=nginx state=present

- name: Copy mime type config
  become: yes
  template: src=conf/mime.types dest=/etc/nginx/mime.types mode=0644 force=yes
  notify:
    - Restart Nginx

- name: Copy core Nginx config
  become: yes
  template: src=conf/nginx.conf dest=/etc/nginx/nginx.conf mode=0644 force=yes
  notify:
    - Restart Nginx
