- name: Ensure system groups exists
  become: yes
  group: name={{user}} state=present

- name: Ensure system user exists
  become: yes
  user: name={{user}} group={{user}}

- name: install scuttlebot (sbot)
  shell: npm install -g scuttlebot
  become: yes

- name: Copy Upstart config
  become: yes
  template: src=upstart.conf dest=/etc/init/{{service}}.conf mode=0644 force=yes
  notify:
    - Restart {{service}}

- name: Ensure the app is running
  become: yes
  service: name={{service}} state=started enabled=yes
